### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Kiffolisk** [rhmodding/Tickompiler#6]
I'm trying to decompile Megamix, and I might have done something wrong.

I run the command:
"java -jar tickompiler.jar d megamix.3ds megamix"

It shows this:
"Decompiling 1 file(s)
Decompiling megamix.3ds" and after a while it just gives me an error (Java heap space)

The ROM name is "megamix", extension is ".3ds" and the folder is named "megamix".
Have I done something wrong?

The entire error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.util.ArrayList.grow(Unknown Source)
        at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
        at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at rhmodding.tickompiler.decompiler.Decompiler.decompile(Decompiler.kt:97)
        at rhmodding.tickompiler.decompiler.Decompiler.decompile$default(Decompiler.kt:64)
        at rhmodding.tickompiler.cli.DecompileCommand$run$$inlined$forEachIndexed$lambda$1.invokeSuspend(DecompileCommand.kt:70)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by chrislo27** [comment]
Hi, Tickompiler is not a decompiler/compiler for the game itself, but for a subset of it called Tickflow, so your usecase is not valid.

You can find more info on Tickompiler commands in the command line by running `java -jar tickompiler.jar --help`.

We cannot offer help on the process of preparing input files, but you might be able to find help on the RHModding Discord server: https://discord.gg/ps4rq53
